<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>DOClouder Management</title>
    <link href="/Public/jquery-easyui-theme/default/easyui.css" rel="stylesheet" type="text/css" />
    <link href="/Public/icons/icon-all.css" rel="stylesheet" type="text/css" />
    <script src="/Public/jquery/jquery-1.11.1.min.js" type="text/javascript"></script>
    <script src="/Public/jquery-easyui-1.3.6/jquery.easyui.min.js" type="text/javascript"></script>
</head>
<body>
<div id="window-login" class="easyui-window" title="404 Not Found"
     data-options="modal:true,closed:false,iconCls:'icon-hamburg-networking',closable:false,minimizable:false,maximizable:false,collapsible:false,resizable:false,draggable:false"
     style="width:600px;padding:20px 70px 20px 70px;">
    <form action="" method="post" id="form-login">
        <div style="margin-bottom:10px; font-size: 50px; font-weight: bold;">
            404 Not Found
        </div>
        <div style="margin-bottom:20px;">
            You can try to access the <a href="/User/start">Login page</a>
        </div>
    </form>
</div>
</body>
</html>