<link rel="stylesheet" type="text/css" href="/public/webuploader/css/webuploader.css" />
<link rel="stylesheet" type="text/css" href="/public/webuploader/exam/image-upload/style.css" />
<div id="wrapper">
    <div id="container">
        <!--头部，相册选择和格式选择-->

        <div id="uploader">
            <div class="queueList">
                <div id="dndArea" class="placeholder">
                    <div id="filePicker"></div>
                    <p>或将文档拖到这里，单次最多可选20个文档</p>
                </div>
            </div>
            <div class="statusBar" style="display:none;">
                <div class="progress">
                    <span class="text">0%</span>
                    <span class="percentage"></span>
                </div><div class="info"></div>
                <div class="btns">
                    <div id="filePicker2"></div><div class="uploadBtn">开始上传</div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/public/webuploader/exam/image-upload/jquery.js"></script>
<script type="text/javascript" src="/public/webuploader/dist/webuploader.js"></script>
<script type="text/javascript" src="/public/webuploader/exam/image-upload/upload.js"></script>