<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html style="width:100%;height:100%;overflow:hidden">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>防止panel,dialog,window窗口超出父元素边界 - jQuery EasyUI Demo</title>
	<link rel="stylesheet" type="text/css" href="/js/themes/default/easyui.css">
	<link rel="stylesheet" type="text/css" href="/js/themes/icon.css">
	<link rel="stylesheet" type="text/css" href="/js/demo.css">
	<script type="text/javascript" src="/js/jquery.min.js"></script>
	<script type="text/javascript" src="/js/jquery.easyui.min.js"></script>
	{literal}
	<script>
		function setOverflow(){
			$('#parentDom').css({"overflow":"auto"});
		}
		var easyuiPanelOnMove = function(left, top) {/* 防止超出浏览器边界 */
			var parentObj = $(this).panel('panel').parent();
    		if (left < 0) {
        		$(this).window('move', {
            		left : 1
        		});
    		}
    		if (top < 0) {
        		$(this).window('move', {
            		top : 1
        		});
    		}
    		var width = $(this).panel('options').width;
    		var height = $(this).panel('options').height;
    		var right = left + width;
    		var buttom = top + height;
    		var parentWidth = parentObj.width();
    		var parentHeight = parentObj.height();
			if(parentObj.css("overflow")=="hidden"){
				if(left > parentWidth-width){
					$(this).window('move', {
            			"left":parentWidth-width
        		
					});
				}
				if(top > parentHeight-height){
					$(this).window('move', {
            			"top":parentHeight-height
        			});
				}
			}
		}
		$.fn.panel.defaults.onMove = easyuiPanelOnMove;
		$.fn.window.defaults.onMove = easyuiPanelOnMove;
		$.fn.dialog.defaults.onMove = easyuiPanelOnMove;
	</script>
	{/literal}
</head>
<body style="height:100%;width:100%;overflow:hidden;border:none;" >
	<h2>本页面仅仅演示Window</h2>
	<div class="demo-info">
		<div class="demo-tip icon-tip"></div>
		<div>试着拖动页面中的两个window,对于inner的window，将父元素的DOM设置为auto再试试效果.</div>
	</div>
	
	<div style="margin:10px 0">
		<a href="javascript:void(0)" class="easyui-linkbutton" onclick="setOverflow()">设置父元素的overflow属性为auto再试试</a>
	</div>
	<div id="parentDom" style="position:relative;width:400px;height:300px;border:1px solid #ccc;overflow:hidden;">
		<div class="easyui-window" title="Inline Window" inline="true" style="width:250px;height:150px;padding:10px">
			This window stay inside its parent
		</div>
	</div>
	<div id="w" class="easyui-window" title="My Window" iconCls="icon-save" style="width:500px;height:200px;padding:5px;">
		<div class="easyui-layout" fit="true">
			<div region="center" border="false" style="padding:10px;background:#fff;border:1px solid #ccc;">
				jQuery EasyUI framework help you build your web page easily.
				<br/><br/>
				click <a href="#" onclick="test()">here</a> to popup another window.
			</div>
			<div region="south" border="false" style="text-align:right;padding:5px 0;">
				<a class="easyui-linkbutton" iconCls="icon-ok" href="javascript:void(0)" onclick="resize()">Ok</a>
				<a class="easyui-linkbutton" iconCls="icon-cancel" href="javascript:void(0)" onclick="resize()">Cancel</a>
			</div>
		</div>
	</div>
	<div id="test" class="easyui-window" closed="true" modal="true" title="Test Window" style="width:300px;height:100px;"></div>
</body>
</html>