<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>{$_lang.title}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <link href="/public/jquery-easyui-theme/default/easyui.css" rel="stylesheet" type="text/css" />
    <link href="/public/jquery-easyui-theme/icon.css" rel="stylesheet" type="text/css" />
    <link href="/public/icons/icon-all.css" rel="stylesheet" type="text/css" />

    <!--<script src="/public/jquery/jquery-1.11.1.js" type="text/javascript"></script>-->
    <script src="/public/js/jquery.min.js" type="text/javascript"></script>

    <script src="/public/jquery-easyui-1.3.6/jquery.easyui.min.js" type="text/javascript"></script>
    <script src="/public/jquery-easyui-1.3.6/plugins/jquery-easyui-datagridview/datagrid-groupview.js" type="text/javascript"></script>
    <script src="/public/jquery-easyui-1.3.6/plugins/jquery-easyui-datagridview/datagrid-detailview.js" type="text/javascript"></script>
    <script src="/public/jquery-easyui-1.4.4/locale/easyui-lang-{if $_lang_key=='ch'}zh_CN{else}{$_lang_key}{/if}.js" type="text/javascript"></script>

    <script src="/public/jquery.jdirk.js" type="text/javascript"></script>
    <!--<script src="release/jquery.jdirk.min.js"></script>-->


    <link href="/public/jeasyui-extensions/jeasyui.extensions.css" rel="stylesheet" type="text/css" />

    <!--    <script src="/public/jeasyui-extensions/jeasyui.extensions.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.progressbar.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.slider.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.linkbutton.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.form.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.validatebox.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.combo.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.combobox.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.menu.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.searchbox.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.panel.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.window.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.dialog.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.layout.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.tree.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.datagrid.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.treegrid.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.combogrid.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.combotree.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.tabs.js" type="text/javascript"></script>
        <script src="/public/jeasyui-extensions/jeasyui.extensions.theme.js" type="text/javascript"></script>-->
    <script src="/public/release/jeasyui.extensions.all.min.js" type="text/javascript"></script>

    <script src="/public/icons/jeasyui.icons.all.js" type="text/javascript"></script>
    <!--<script src="/public/release/jeasyui.icons.all.min.js"></script>-->

    <script src="/public/jeasyui-extensions/jeasyui.extensions.icons.js" type="text/javascript"></script>
    <script src="/public/jeasyui-extensions/jeasyui.extensions.gridselector.js" type="text/javascript"></script>
    <!--    <script src="/public/plugins/My97DatePicker/WdatePicker.js" type="text/javascript"></script>-->
    <!--<script src="/public/plugins/uploadify/jquery.uploadify.min.js" type="text/javascript"></script>-->

    <script src="/public/jeasyui-extensions/jquery.toolbar.js" type="text/javascript"></script>
    <script src="/public/jeasyui-extensions/jquery.comboicons.js" type="text/javascript"></script>
    <script src="/public/jeasyui-extensions/jquery.comboselector.js" type="text/javascript"></script>
    <script src="/public/jeasyui-extensions/jquery.my97.js" type="text/javascript"></script>
    <script src="/public/jeasyui-extensions/jquery.portal.js" type="text/javascript"></script>

    <!--导入首页启动时需要的相应资源文件(首页相应功能的 js 库、css样式以及渲染首页界面的 js 文件)-->
    <script src="/public/asset/_language_js_{$_lang_key}.js" type="text/javascript"></script>
    <script src="/public/core/admin.common.js" type="text/javascript"></script>
    <script src="/public/core/admin.datagrid.js" type="text/javascript"></script>
    <script src="/public/common/common.js" type="text/javascript"></script>

    <script src="/public/common/index.js" type="text/javascript"></script>
    <link href="/public/common/index.css" rel="stylesheet" />
    <!--<script src="/public/common/index-startup.js" type="text/javascript"></script>-->

    <script src="/public/core/AkTable.js" type="text/javascript"></script>
    <script src="/public/core/admin.process.manager.js" type="text/javascript"></script>
    <script src="/public/core/admin.folder.js" type="text/javascript"></script>
    <script src="/public/core/admin.menu.js" type="text/javascript"></script>


    {literal}

    <!--接口文档的样式-->
    <style type="text/css">
        body { padding: 0px; margin: 0px; }
        #docContainer { padding-left: 10px; padding-right: 10px; font-size: 14px; font-family: Arial,Helvetica,"Nimbus Sans L",sans-serif; }
        .syntaxhighlighter a, .syntaxhighlighter div, .syntaxhighlighter code, .syntaxhighlighter table, .syntaxhighlighter table td, .syntaxhighlighter table tr, .syntaxhighlighter table tbody, .syntaxhighlighter table thead, .syntaxhighlighter table caption, .syntaxhighlighter textarea
        {
            font-size: 13px !important; line-height: 16px !important;
        }
        a {color: #eb6100; text-decoration: none;}

        h3 { margin: 12px 0px; font-size: 20px; font-weight: bold; }
        h4 { margin: 10px 0px; color: rgb(204, 0, 0); font-size: 16px; font-weight: bold; }
        h5 { margin: 5px 0px; color: rgb(153, 0, 0); font-size: 14px; font-weight: bold; }
        .doc-table { margin-left: 9px; border-collapse: collapse; border-spacing: 0; }
        .doc-table th { padding: 0.3em 0.7em; border: 1px solid rgb(140, 172, 187); font-weight: bold; min-width: 60px; }
        .doc-table td { padding: 0.3em 0.7em; border: 1px solid rgb(140, 172, 187); }
        .doc-table th { background: rgb(238, 238, 238); }
        .doc-table pre { background: rgb(250, 250, 250); padding: 5px; color: rgb(0, 102, 0); font-family: Verdana; font-size: 12px; }
        .stress { font-weight: bold; color: Red; }
        .example { color: Blue; text-decoration: none; }
    </style>
    <script type="application/javascript">
        $(function(){
            var t = $("#navMenu_Tree_test");

            t.tree({
                url         : "/public/common/nav-doc-menu-data.json",
                animate     : true,
                lines       : true,
                toggleOnClick: true,
                selectOnContextMenu: true,
                showOption  : true,
                filter: function(q, node){
                    var is_show = false;
                    if(node.text.toLowerCase().indexOf(q.toLowerCase()) >= 0){
                        is_show = true;
                    }

                    return is_show;
                },
                onClick: function (node) {

                },
                onLoadSuccess: function (node, data) {

                },
                onLoadError: function(){
                    $.easyui.loaded(westCenterLayout);
                },
                contextMenu: [
                    {
                        text: "打开/转到", iconCls: "icon-standard-application-add",
                        disabled: function (e, node) { return node.attributes && node.attributes.href ? false : true; },
                        handler: function (e, node) {
                            window.mainpage.addModuleTab(node);
                        }
                    }, "-",
                    { text: "添加至个人收藏", iconCls: "icon-standard-feed-add", disabled: function (e, node) { return !t.tree("isLeaf", node.target); }, handler: function (e, node) { window.mainpage.nav.addFavo(node.id); } },
                    { text: "重命名", iconCls: "icon-hamburg-pencil", handler: function (e, node) { t.tree("beginEdit", node.target); } }, "-",
                    { text: "刷新", iconCls: "icon-cologne-refresh", handler: function (e, node) { window.mainpage.nav.refreshTree(); } }
                ],
                onAfterEdit: function (node) { window.mainpage.nav.rename(node.id, node.text); }
            });
        });

    </script>

    {/literal}
</head>
<body>
<ul id="navMenu_Tree_test"  class="easyui-tree">xxx</ul>

</body>
</html>