<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{$_lang.title}</title>
    <link href="/Public/jquery-easyui-theme/{$themeName}/easyui.css" rel="stylesheet" type="text/css" />
    <link href="/Public/jquery-easyui-theme/icon.css" rel="stylesheet" type="text/css" />
    <link href="/Public/icons/icon-all.css" rel="stylesheet" type="text/css" />

    <script src="/Public/jquery/jquery-1.11.1.js" type="text/javascript"></script>
    <!--<script src="/Public/jquery/jquery-1.11.1.min.js"></script>-->

    <script src="/Public/jquery-easyui-1.3.6/jquery.easyui.min.js" type="text/javascript"></script>
    <script src="/Public/jquery-easyui-1.3.6/locale/easyui-lang-zh_CN.js" type="text/javascript"></script>

    <script src="/Public/jquery.jdirk.js" type="text/javascript"></script>
    <!--<script src="release/jquery.jdirk.min.js"></script>-->

    <link href="/Public/jeasyui-extensions/jeasyui.extensions.css" rel="stylesheet" type="text/css" />

    <script src="/Public/release/jeasyui.extensions.all.min.js" type="text/javascript"></script>

    <script src="/Public/icons/jeasyui.icons.all.js" type="text/javascript"></script>
    <!--<script src="/Public/release/jeasyui.icons.all.min.js"></script>-->

    <script src="/public/asset/_language_js_{$_lang_key}.js" type="text/javascript"></script>
    <script src="/public/common/const.js" type="text/javascript"></script>
    {literal}

    <script language="javascript" type="application/javascript">
        function checkForm()
        {
            var username = $.trim($("#username").val());
            var password = $.trim($("#password").val());
            var verify = $.trim($("#verify").val());
            var language = $.trim($("#language").combobox("getValue"));

            if(!username || !password || !verify)
            {
                $.messager.show("Message", "Username, password and verify code are requested!", "warning");
                return false;
            }

            var postData = {
                username : username,
                password : password,
                verify   : verify,
                language : language
            };

            $.ajax({
                url     : "/User/start",
                type    : "POST",
                dataType: "json",
                data    : postData,
                success : function (backData) {
                    if(backData.status_code == RESPONSE_SUCCESS){
                        top.location.href = "/";
                    }else{
                        $("#img-verify-code").attr("src", '/User/verify/time/'+Math.random());
                    }

                    $.messager.show("Message", backData.status_message, "info", "center");
                }
            });
        }

        $(function(){
            $("#verify").keyup(function(event){
                if(event.keyCode ==13){
                    checkForm();
                }
            });

            $("#username").focus();
        })
    </script>
    {/literal}

</head>
<body>
<div id="window-login" class="easyui-window" title="登录/Login" data-options="modal:true,closed:false,iconCls:'icon-hamburg-networking',closable:false,minimizable:false,maximizable:false"
     style="width:400px;padding:20px 70px 20px 70px;">
    <form action="" method="post" id="form-login">
        <div style="margin-bottom:10px">
            <input class="easyui-validatebox" id="username" name="username" style="width:100%;height:30px;" data-options="prompt:'用户名称',iconCls:'icon-hamburg-user',iconWidth:38">
        </div>
        <div style="margin-bottom:20px">
            <input class="easyui-validatebox" id="password" name="password" type="password" style="width:100%;height:30px;" data-options="prompt:'登录密码',iconCls:'icon-hamburg-lock',iconWidth:38">
        </div>
        <div style="margin-bottom:20px">
            <select id="language" class="easyui-combobox" name="language" style="width:200px;">
                <option value="en">English</option>
                <option value="ch">中文</option>
            </select>
        </div>
        <div style="margin-bottom:20px">
            <input class="easyui-validatebox" type="text" id="verify" name="verify" style="width:50%;height:30px;" data-options="prompt:'验证码'">
            <img style="cursor: pointer; margin:0 0 0 3px ; vertical-align:middle; height:26px;" src="/User/verify" id="img-verify-code" onclick="javascript:this.src='/User/verify/time/'+Math.random();" >
        </div>

        <div>
            <a href="javascript:;" onclick="checkForm()" class="easyui-linkbutton" data-options="iconCls:'icon-ok'" style="padding:5px 0px;width:100%;">
                <span style="font-size:14px;">登录/Login</span>
            </a>
        </div>
    </form>
</div>
</body>
</html>